GET http://localhost:3000/alumnos
###
GET http://localhost:3000/alumnos/22
###
GET http://localhost:3000/docentes
###
GET http://localhost:3000/docentes/
###
POST  http://localhost:3000/alumnos
Content-Type: application/json

{
    "id": 4,
    "nombre": "Lucia",
    "carrera": "Perito Mercantil"
}
###
PUT  http://localhost:3000/alumnos/4
Content-Type: application/json

{
    "id": 5,
    "nombre": "Mile Granados",
    "carrera": "Ingenieria industrial"
}

###
GET http://localhost:3000/alumnos/5
###
DELETE http://localhost:3000/alumnos/55
###
USE http://localhost:3000/alumnos/5
