GET http://localhost:3000/alumnos
###
GET http://localhost:3000/alumnos/1002
###
GET http://localhost:3000/docentes
###
GET http://localhost:3000/docentes/
###
POST  http://localhost:3000/alumnos
Content-Type: application/json

{
    "legajo": 1010,
    "nombre": "Romualdo",
    "carrera": "Famaseutico",
    "correo": "romualado@email.com"
}
###
PUT  http://localhost:3000/alumnos/1008
Content-Type: application/json

{
    "legajo": 1008,
    "nombre": "Freitas",
    "carrera": "Ingenieria idraulica",
    "correo": "freitas@email.com"
}

###
GET http://localhost:3000/alumnos/5
###
DELETE http://localhost:3000/alumnos/1008

###
USE http://localhost:3000/alumnos/5
